parameters:
    sylius_order.expiration_method_codes: []
    mangoweb_sylius_extended_channels_hello_bar_types:
        error: 'Error'
        success: 'Success'
        info: 'Info'
        warning: 'Warning'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    mango_sylius.extended_channels.email_sender.adapter.custom:
        autowire: false
        autoconfigure: false
        public: true
        parent: sylius.email_sender.adapter.abstract
        class: MangoSylius\ExtendedChannelsPlugin\Service\SwiftMailerAdapter
        arguments:
            $dispatcher: '@event_dispatcher'
            $mailer: '@mailer'
            $logger: '@logger'

    MangoSylius\ExtendedChannelsPlugin\Service\OrderEmailManager:
        decorates: sylius.email_manager.order
        arguments:
            $emailSender: '@sylius.email_sender'
            $channelContext: '@sylius.context.channel'

    MangoSylius\ExtendedChannelsPlugin\Form\Extension\TaxonTypeExtension:
        tags:
            -   name: form.type_extension
                extended_type: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonType

    MangoSylius\ExtendedChannelsPlugin\Form\Extension\ExtendedChannelExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType

    MangoSylius\ExtendedChannelsPlugin\Form\Extension\ProductExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductType

    MangoSylius\ExtendedChannelsPlugin\Form\Extension\ProductVariantExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType

    MangoSylius\ExtendedChannelsPlugin\Form\Type\HelloBarType:
        tags:
            - name: form.type
        arguments:
            - '%mangoweb_sylius_extended_channels_hello_bar_types%'
            - '%mangoweb_extended_channels_plugin.model.hello_bar.class%'
            - ['sylius']

    MangoSylius\ExtendedChannelsPlugin\Form\Type\HelloBarTranslationType:
        tags:
            - name: form.type
        arguments: ['%mangoweb_extended_channels_plugin.model.hello_bar_translation.class%', ['sylius']]

    MangoSylius\ExtendedChannelsPlugin\Form\Type\BulkManageProductCategoriesType:
        tags:
            - name: form.type

    sylius.email_manager.order: '@MangoSylius\ExtendedChannelsPlugin\Service\OrderEmailManager'
    Sylius\Bundle\ShopBundle\EmailManager\OrderEmailManagerInterface: '@MangoSylius\ExtendedChannelsPlugin\Service\OrderEmailManager'

    MangoSylius\ExtendedChannelsPlugin\Command\UpdateProductPriceByExchangeRatesCommand:
        tags:
            - name: 'console.command'
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'
            $logger: '@sylius_fixtures.logger'
            $exchangeRateRepository: '@sylius.repository.exchange_rate'
            $productVariantRepository: '@sylius.repository.product_variant'
            $channelRepository: '@sylius.repository.channel'
            $currencyConverter: '@sylius.currency_converter'

    MangoSylius\ExtendedChannelsPlugin\Command\UpdateExchangeRatesCommand:
        tags:
            - name: 'console.command'
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'
            $logger: '@sylius_fixtures.logger'
            $exchangeRateRepository: '@sylius.repository.exchange_rate'

    MangoSylius\ExtendedChannelsPlugin\Service\MangoUnpaidOrdersStateUpdater:
        arguments:
            $orderRepository: '@sylius.repository.order'
            $stateMachineFactory: '@sm.factory'
            $expirationPeriod: '%sylius_order.order_expiration_period%'
            $expirationMethodCodes: '%sylius_order.expiration_method_codes%'

    MangoSylius\ExtendedChannelsPlugin\Command\MangoCancelUnpaidOrdersCommand:
        tags:
            - name: 'console.command'
        arguments:
            $unpaidCartsStateUpdater: '@MangoSylius\ExtendedChannelsPlugin\Service\MangoUnpaidOrdersStateUpdater'
            $entityManager: '@doctrine.orm.default_entity_manager'
            $expirationPeriod: '%sylius_order.order_expiration_period%'
            $expirationMethodCodes: '%sylius_order.expiration_method_codes%'

    MangoSylius\ExtendedChannelsPlugin\Menu\AdminMenuListener:
        tags:
            - name: kernel.event_listener
              event: sylius.menu.admin.product.update
              method: addButtonsToProduct

            - name: kernel.event_listener
              event: sylius.menu.admin.main
              method: addAdminMenuItems

    MangoSylius\ExtendedChannelsPlugin\Controller\DuplicateController:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $router: '@router'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $productRepository: '@sylius.repository.product'
            $productVariantRepository: '@sylius.repository.product_variant'
            $productDuplicator: '@MangoSylius\ExtendedChannelsPlugin\Service\ProductDuplicator'

    MangoSylius\ExtendedChannelsPlugin\Controller\ManageProductCategoriesController:
        public: true
        arguments:
            $router: '@router'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $productRepository: '@sylius.repository.product'
            $twig: '@twig'
            $entityManager: '@doctrine.orm.default_entity_manager'
            $formFactory: '@form.factory'
            $eventDispatcher: '@event_dispatcher'
            $productFactory: '@sylius.custom_factory.product'
            $productTaxonFactory: '@sylius.factory.product_taxon'

    MangoSylius\ExtendedChannelsPlugin\Service\ProductDuplicator:
        arguments:
            $imageUploader: '@sylius.image_uploader'
            $productRepository: '@sylius.repository.product'
            $productVariantRepository: '@sylius.repository.product_variant'
            $dataManager: '@liip_imagine.data.manager'

    MangoSylius\ExtendedChannelsPlugin\Twig\HelloBarExtension:
        tags: ['twig.extension']
        public: true
        arguments:
            $channelContext: '@sylius.context.channel.composite'
            $helloBarRepository: '@mangoweb_extended_channels_plugin.repository.hello_bar'
