#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# some value to avoid 'invalid environment variable: ' docker compose error
APP_ENV_DEFINITION='EMPTY_NOTHINGNESS=NOTHING'
if [ -n "${APP_ENV:-}" ]; then
  APP_ENV_DEFINITION="APP_ENV=${APP_ENV}"
fi

source "${DIR}/_tty.sh"

CURRENT_USER_ID=$(id -u)
CURRENT_GROUP_ID=$(id -g)

if [ "$(docker compose ps php | grep --count Up)" -gt 0 ]; then
	docker_compose_exec \
		--user="${CURRENT_USER_ID}:${CURRENT_GROUP_ID}" \
		--env="${APP_ENV_DEFINITION}" \
		php php "$@"
else
    # without --entrypoint=/usr/local/bin/php as that may break loading of php.ini
	docker_compose_run \
		--entrypoint=php \
		--user="${CURRENT_USER_ID}:${CURRENT_GROUP_ID}" \
		--env="${APP_ENV_DEFINITION}" \
		php "$@"
fi
